insert into Food (NameOfFood, Category, CaloryCount) values ('Rhinoceros, white', 'desert', 58);
insert into Food (NameOfFood, Category, CaloryCount) values ('Tarantula', 'desert', 41);
insert into Food (NameOfFood, Category, CaloryCount) values ('Plains zebra', 'desert', 7);
insert into Food (NameOfFood, Category, CaloryCount) values ('Red-tailed cockatoo', 'side', 79);
insert into Food (NameOfFood, Category, CaloryCount) values ('African black crake', 'side', 77);
insert into Food (NameOfFood, Category, CaloryCount) values ('Moorhen, purple', 'main', 59);
insert into Food (NameOfFood, Category, CaloryCount) values ('Squirrel, uinta ground', 'main', 87);
insert into Food (NameOfFood, Category, CaloryCount) values ('Thrasher, curve-billed', 'main', 46);
insert into Food (NameOfFood, Category, CaloryCount) values ('House sparrow', 'main', 14);
insert into Food (NameOfFood, Category, CaloryCount) values ('Flamingo, chilean', 'desert', 51);
insert into Food (NameOfFood, Category, CaloryCount) values ('Giant girdled lizard', 'side', 76);
insert into Food (NameOfFood, Category, CaloryCount) values ('Burchell''s gonolek', 'desert', 43);
insert into Food (NameOfFood, Category, CaloryCount) values ('Red-tailed hawk', 'desert', 44);
insert into Food (NameOfFood, Category, CaloryCount) values ('Barbet, crested', 'main', 19);
insert into Food (NameOfFood, Category, CaloryCount) values ('Euro wallaby', 'side', 11);
insert into Food (NameOfFood, Category, CaloryCount) values ('Common raccoon', 'main', 33);
insert into Food (NameOfFood, Category, CaloryCount) values ('Jaguarundi', 'main', 28);
insert into Food (NameOfFood, Category, CaloryCount) values ('Black bear', 'desert', 97);
insert into Food (NameOfFood, Category, CaloryCount) values ('Desert kangaroo rat', 'side', 66);
insert into Food (NameOfFood, Category, CaloryCount) values ('Blacksmith plover', 'main', 36);
insert into Food (NameOfFood, Category, CaloryCount) values ('Turaco, violet-crested', 'main', 56);
insert into Food (NameOfFood, Category, CaloryCount) values ('Anteater, giant', 'side', 87);
insert into Food (NameOfFood, Category, CaloryCount) values ('Marabou stork', 'side', 76);
insert into Food (NameOfFood, Category, CaloryCount) values ('Rhea, common', 'desert', 55);
insert into Food (NameOfFood, Category, CaloryCount) values ('Goldeneye, common', 'side', 67);
insert into Food (NameOfFood, Category, CaloryCount) values ('Flamingo, greater', 'side', 62);
insert into Food (NameOfFood, Category, CaloryCount) values ('Flicker, field', 'side', 54);
insert into Food (NameOfFood, Category, CaloryCount) values ('Porcupine, crested', 'main', 56);
insert into Food (NameOfFood, Category, CaloryCount) values ('Collared peccary', 'desert', 9);
insert into Food (NameOfFood, Category, CaloryCount) values ('Egyptian goose', 'desert', 71);
insert into Food (NameOfFood, Category, CaloryCount) values ('White-headed vulture', 'desert', 1);
insert into Food (NameOfFood, Category, CaloryCount) values ('Stone sheep', 'desert', 3);
insert into Food (NameOfFood, Category, CaloryCount) values ('Grenadier, purple', 'side', 84);
insert into Food (NameOfFood, Category, CaloryCount) values ('Colobus, magistrate black', 'desert', 34);
insert into Food (NameOfFood, Category, CaloryCount) values ('Stork, saddle-billed', 'desert', 56);
insert into Food (NameOfFood, Category, CaloryCount) values ('Squirrel, richardson''s ground', 'main', 35);
insert into Food (NameOfFood, Category, CaloryCount) values ('Red meerkat', 'main', 44);
insert into Food (NameOfFood, Category, CaloryCount) values ('White-rumped vulture', 'side', 52);
insert into Food (NameOfFood, Category, CaloryCount) values ('Cat, tiger', 'desert', 97);
insert into Food (NameOfFood, Category, CaloryCount) values ('Heron, gray', 'side', 47);
insert into Food (NameOfFood, Category, CaloryCount) values ('Dove, laughing', 'main', 93);
insert into Food (NameOfFood, Category, CaloryCount) values ('Boar, wild', 'desert', 18);
insert into Food (NameOfFood, Category, CaloryCount) values ('Kafue flats lechwe', 'main', 75);
insert into Food (NameOfFood, Category, CaloryCount) values ('Laughing dove', 'desert', 11);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bear, american black', 'side', 95);
insert into Food (NameOfFood, Category, CaloryCount) values ('Stork, greater adjutant', 'main', 54);
insert into Food (NameOfFood, Category, CaloryCount) values ('North American river otter', 'desert', 58);
insert into Food (NameOfFood, Category, CaloryCount) values ('Otter, african clawless', 'desert', 65);
insert into Food (NameOfFood, Category, CaloryCount) values ('Mongoose, small indian', 'side', 34);
insert into Food (NameOfFood, Category, CaloryCount) values ('Buttermilk snake', 'side', 72);
insert into Food (NameOfFood, Category, CaloryCount) values ('Grey-footed squirrel', 'desert', 33);
insert into Food (NameOfFood, Category, CaloryCount) values ('Lesser mouse lemur', 'side', 78);
insert into Food (NameOfFood, Category, CaloryCount) values ('Spotted-tailed quoll', 'main', 59);
insert into Food (NameOfFood, Category, CaloryCount) values ('Wallaby, red-necked', 'main', 43);
insert into Food (NameOfFood, Category, CaloryCount) values ('White-winged tern', 'desert', 49);
insert into Food (NameOfFood, Category, CaloryCount) values ('Sportive lemur', 'desert', 50);
insert into Food (NameOfFood, Category, CaloryCount) values ('Asian foreset tortoise', 'side', 89);
insert into Food (NameOfFood, Category, CaloryCount) values ('Pallas''s fish eagle', 'side', 75);
insert into Food (NameOfFood, Category, CaloryCount) values ('Black-crowned night heron', 'side', 31);
insert into Food (NameOfFood, Category, CaloryCount) values ('Currasow (unidentified)', 'desert', 26);
insert into Food (NameOfFood, Category, CaloryCount) values ('Spectacled caiman', 'main', 37);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bustard, denham''s', 'desert', 81);
insert into Food (NameOfFood, Category, CaloryCount) values ('Eurasian badger', 'side', 72);
insert into Food (NameOfFood, Category, CaloryCount) values ('Rat, arboral spiny', 'side', 51);
insert into Food (NameOfFood, Category, CaloryCount) values ('Skimmer, four-spotted', 'main', 48);
insert into Food (NameOfFood, Category, CaloryCount) values ('Dark-winged trumpeter', 'main', 64);
insert into Food (NameOfFood, Category, CaloryCount) values ('Nile crocodile', 'main', 10);
insert into Food (NameOfFood, Category, CaloryCount) values ('Red-billed toucan', 'side', 20);
insert into Food (NameOfFood, Category, CaloryCount) values ('Galapagos sea lion', 'desert', 69);
insert into Food (NameOfFood, Category, CaloryCount) values ('Ass, asiatic wild', 'desert', 48);
insert into Food (NameOfFood, Category, CaloryCount) values ('Boa, cook''s tree', 'side', 47);
insert into Food (NameOfFood, Category, CaloryCount) values ('Blue-tongued skink', 'side', 20);
insert into Food (NameOfFood, Category, CaloryCount) values ('Wallaby, dama', 'desert', 2);
insert into Food (NameOfFood, Category, CaloryCount) values ('Boa, malagasy ground', 'main', 47);
insert into Food (NameOfFood, Category, CaloryCount) values ('Lizard, frilled', 'main', 4);
insert into Food (NameOfFood, Category, CaloryCount) values ('Nutcracker, clark''s', 'desert', 70);
insert into Food (NameOfFood, Category, CaloryCount) values ('Cat, jungle', 'main', 53);
insert into Food (NameOfFood, Category, CaloryCount) values ('Giant armadillo', 'desert', 100);
insert into Food (NameOfFood, Category, CaloryCount) values ('Javanese cormorant', 'desert', 13);
insert into Food (NameOfFood, Category, CaloryCount) values ('Four-horned antelope', 'main', 92);
insert into Food (NameOfFood, Category, CaloryCount) values ('Caribou', 'side', 48);
insert into Food (NameOfFood, Category, CaloryCount) values ('European shelduck', 'side', 76);
insert into Food (NameOfFood, Category, CaloryCount) values ('Gray langur', 'desert', 100);
insert into Food (NameOfFood, Category, CaloryCount) values ('Ibis, puna', 'side', 92);
insert into Food (NameOfFood, Category, CaloryCount) values ('Waxbill, violet-eared', 'side', 47);
insert into Food (NameOfFood, Category, CaloryCount) values ('Antechinus, brown', 'main', 98);
insert into Food (NameOfFood, Category, CaloryCount) values ('Black-footed ferret', 'main', 83);
insert into Food (NameOfFood, Category, CaloryCount) values ('Grebe, little', 'main', 33);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bear, american black', 'main', 18);
insert into Food (NameOfFood, Category, CaloryCount) values ('South American meadowlark (unidentified)', 'desert', 42);
insert into Food (NameOfFood, Category, CaloryCount) values ('Rhesus macaque', 'main', 67);
insert into Food (NameOfFood, Category, CaloryCount) values ('Silver-backed fox', 'main', 100);
insert into Food (NameOfFood, Category, CaloryCount) values ('Vulture, lappet-faced', 'main', 36);
insert into Food (NameOfFood, Category, CaloryCount) values ('Grey heron', 'desert', 85);
insert into Food (NameOfFood, Category, CaloryCount) values ('Asian false vampire bat', 'desert', 86);
insert into Food (NameOfFood, Category, CaloryCount) values ('Macaque, japanese', 'desert', 32);
insert into Food (NameOfFood, Category, CaloryCount) values ('Goose, andean', 'desert', 77);
insert into Food (NameOfFood, Category, CaloryCount) values ('Heron, green', 'main', 31);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bee-eater, nubian', 'desert', 38);
insert into Food (NameOfFood, Category, CaloryCount) values ('Hornbill, yellow-billed', 'main', 62);
insert into Food (NameOfFood, Category, CaloryCount) values ('Beaver, eurasian', 'main', 91);
insert into Food (NameOfFood, Category, CaloryCount) values ('Hartebeest, coke''s', 'main', 38);
insert into Food (NameOfFood, Category, CaloryCount) values ('Hudsonian godwit', 'desert', 63);
insert into Food (NameOfFood, Category, CaloryCount) values ('Magellanic penguin', 'desert', 90);
insert into Food (NameOfFood, Category, CaloryCount) values ('Cockatoo, red-tailed', 'desert', 44);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bushbaby, large-eared', 'side', 86);
insert into Food (NameOfFood, Category, CaloryCount) values ('Orca', 'side', 69);
insert into Food (NameOfFood, Category, CaloryCount) values ('Mississippi alligator', 'desert', 98);
insert into Food (NameOfFood, Category, CaloryCount) values ('Pocket gopher (unidentified)', 'side', 85);
insert into Food (NameOfFood, Category, CaloryCount) values ('American Virginia opossum', 'side', 37);
insert into Food (NameOfFood, Category, CaloryCount) values ('Southern boubou', 'side', 70);
insert into Food (NameOfFood, Category, CaloryCount) values ('Ostrich', 'desert', 75);
insert into Food (NameOfFood, Category, CaloryCount) values ('Pied avocet', 'side', 32);
insert into Food (NameOfFood, Category, CaloryCount) values ('Roe deer', 'main', 74);
insert into Food (NameOfFood, Category, CaloryCount) values ('Egyptian viper', 'side', 11);
insert into Food (NameOfFood, Category, CaloryCount) values ('Russian dragonfly', 'desert', 39);
insert into Food (NameOfFood, Category, CaloryCount) values ('South African hedgehog', 'main', 29);
insert into Food (NameOfFood, Category, CaloryCount) values ('Jaeger, long-tailed', 'desert', 33);
insert into Food (NameOfFood, Category, CaloryCount) values ('Eagle owl (unidentified)', 'side', 17);
insert into Food (NameOfFood, Category, CaloryCount) values ('Caracal', 'main', 13);
insert into Food (NameOfFood, Category, CaloryCount) values ('Lemur, lesser mouse', 'main', 14);
insert into Food (NameOfFood, Category, CaloryCount) values ('Tortoise, indian star', 'side', 1);
insert into Food (NameOfFood, Category, CaloryCount) values ('African darter', 'desert', 13);
insert into Food (NameOfFood, Category, CaloryCount) values ('Yellow-rumped siskin', 'desert', 80);
insert into Food (NameOfFood, Category, CaloryCount) values ('Jacana, african', 'main', 77);
insert into Food (NameOfFood, Category, CaloryCount) values ('Red-shouldered glossy starling', 'side', 13);
insert into Food (NameOfFood, Category, CaloryCount) values ('Dragon, asian water', 'main', 33);
insert into Food (NameOfFood, Category, CaloryCount) values ('Springbuck', 'side', 9);
insert into Food (NameOfFood, Category, CaloryCount) values ('Helmeted guinea fowl', 'side', 38);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bat, little brown', 'side', 37);
insert into Food (NameOfFood, Category, CaloryCount) values ('Lion, mountain', 'main', 6);
insert into Food (NameOfFood, Category, CaloryCount) values ('Skunk, striped', 'main', 98);
insert into Food (NameOfFood, Category, CaloryCount) values ('Screamer, crested', 'side', 19);
insert into Food (NameOfFood, Category, CaloryCount) values ('Tapir, brazilian', 'main', 61);
insert into Food (NameOfFood, Category, CaloryCount) values ('Monitor, two-banded', 'desert', 27);
insert into Food (NameOfFood, Category, CaloryCount) values ('Chestnut weaver', 'desert', 63);
insert into Food (NameOfFood, Category, CaloryCount) values ('Blacksmith plover', 'side', 62);
insert into Food (NameOfFood, Category, CaloryCount) values ('Agouti', 'side', 54);
insert into Food (NameOfFood, Category, CaloryCount) values ('Jaeger, long-tailed', 'desert', 93);
insert into Food (NameOfFood, Category, CaloryCount) values ('Knob-nosed goose', 'main', 51);
insert into Food (NameOfFood, Category, CaloryCount) values ('Waxbill, black-cheeked', 'side', 58);
insert into Food (NameOfFood, Category, CaloryCount) values ('Tamandua, southern', 'desert', 87);
insert into Food (NameOfFood, Category, CaloryCount) values ('Owl, burrowing', 'side', 53);
insert into Food (NameOfFood, Category, CaloryCount) values ('Armadillo, seven-banded', 'side', 98);
insert into Food (NameOfFood, Category, CaloryCount) values ('Porcupine, prehensile-tailed', 'desert', 68);
insert into Food (NameOfFood, Category, CaloryCount) values ('Laughing kookaburra', 'main', 25);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bald eagle', 'side', 17);
insert into Food (NameOfFood, Category, CaloryCount) values ('Orca', 'desert', 89);
insert into Food (NameOfFood, Category, CaloryCount) values ('Fowl, helmeted guinea', 'side', 2);
insert into Food (NameOfFood, Category, CaloryCount) values ('Otter, canadian river', 'main', 15);
insert into Food (NameOfFood, Category, CaloryCount) values ('Barking gecko', 'side', 21);
insert into Food (NameOfFood, Category, CaloryCount) values ('Kalahari scrub robin', 'desert', 67);
insert into Food (NameOfFood, Category, CaloryCount) values ('Robin, white-throated', 'main', 30);
insert into Food (NameOfFood, Category, CaloryCount) values ('Waxbill, blue', 'main', 62);
insert into Food (NameOfFood, Category, CaloryCount) values ('Black bear', 'side', 65);
insert into Food (NameOfFood, Category, CaloryCount) values ('Great cormorant', 'desert', 74);
insert into Food (NameOfFood, Category, CaloryCount) values ('Yellow-billed hornbill', 'side', 50);
insert into Food (NameOfFood, Category, CaloryCount) values ('Sage grouse', 'side', 51);
insert into Food (NameOfFood, Category, CaloryCount) values ('Otter, giant', 'desert', 52);
insert into Food (NameOfFood, Category, CaloryCount) values ('Skua, long-tailed', 'main', 65);
insert into Food (NameOfFood, Category, CaloryCount) values ('Fox, cape', 'main', 42);
insert into Food (NameOfFood, Category, CaloryCount) values ('Verreaux''s sifaka', 'desert', 9);
insert into Food (NameOfFood, Category, CaloryCount) values ('Tern, white-winged', 'side', 29);
insert into Food (NameOfFood, Category, CaloryCount) values ('Turkey, wild', 'desert', 53);
insert into Food (NameOfFood, Category, CaloryCount) values ('African porcupine', 'main', 29);
insert into Food (NameOfFood, Category, CaloryCount) values ('Butterfly, canadian tiger swallowtail', 'side', 2);
insert into Food (NameOfFood, Category, CaloryCount) values ('Fisher', 'desert', 52);
insert into Food (NameOfFood, Category, CaloryCount) values ('Marabou stork', 'main', 75);
insert into Food (NameOfFood, Category, CaloryCount) values ('Dove, rock', 'desert', 64);
insert into Food (NameOfFood, Category, CaloryCount) values ('Macaque, rhesus', 'side', 41);
insert into Food (NameOfFood, Category, CaloryCount) values ('Cardinal, black-throated', 'main', 45);
insert into Food (NameOfFood, Category, CaloryCount) values ('Little grebe', 'main', 84);
insert into Food (NameOfFood, Category, CaloryCount) values ('Lion, african', 'desert', 5);
insert into Food (NameOfFood, Category, CaloryCount) values ('Caracal', 'desert', 92);
insert into Food (NameOfFood, Category, CaloryCount) values ('Blue waxbill', 'main', 43);
insert into Food (NameOfFood, Category, CaloryCount) values ('Greylag goose', 'side', 76);
insert into Food (NameOfFood, Category, CaloryCount) values ('African wild cat', 'main', 90);
insert into Food (NameOfFood, Category, CaloryCount) values ('Cockatoo, roseate', 'desert', 82);
insert into Food (NameOfFood, Category, CaloryCount) values ('Desert spiny lizard', 'main', 65);
insert into Food (NameOfFood, Category, CaloryCount) values ('Wallaby, agile', 'side', 41);
insert into Food (NameOfFood, Category, CaloryCount) values ('Woodpecker, downy', 'desert', 8);
insert into Food (NameOfFood, Category, CaloryCount) values ('Greylag goose', 'desert', 32);
insert into Food (NameOfFood, Category, CaloryCount) values ('Australian sea lion', 'desert', 100);
insert into Food (NameOfFood, Category, CaloryCount) values ('Lion, asian', 'side', 33);
insert into Food (NameOfFood, Category, CaloryCount) values ('Lapwing, southern', 'desert', 93);
insert into Food (NameOfFood, Category, CaloryCount) values ('Black rhinoceros', 'main', 71);
insert into Food (NameOfFood, Category, CaloryCount) values ('Crowned eagle', 'side', 22);
insert into Food (NameOfFood, Category, CaloryCount) values ('Black-footed ferret', 'side', 40);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bear, american black', 'desert', 89);
insert into Food (NameOfFood, Category, CaloryCount) values ('Eastern dwarf mongoose', 'main', 55);
insert into Food (NameOfFood, Category, CaloryCount) values ('Racer, american', 'main', 93);
insert into Food (NameOfFood, Category, CaloryCount) values ('Cat, miner''s', 'side', 48);
insert into Food (NameOfFood, Category, CaloryCount) values ('Impala', 'side', 91);
insert into Food (NameOfFood, Category, CaloryCount) values ('Squirrel, indian giant', 'side', 2);
insert into Food (NameOfFood, Category, CaloryCount) values ('White-browed sparrow weaver', 'side', 6);
insert into Food (NameOfFood, Category, CaloryCount) values ('Roller, lilac-breasted', 'desert', 51);
insert into Food (NameOfFood, Category, CaloryCount) values ('Gaur', 'side', 46);
insert into Food (NameOfFood, Category, CaloryCount) values ('Coqui francolin', 'side', 38);
insert into Food (NameOfFood, Category, CaloryCount) values ('Heron, giant', 'side', 7);
insert into Food (NameOfFood, Category, CaloryCount) values ('Chipmunk, least', 'main', 5);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bat, little brown', 'side', 44);
insert into Food (NameOfFood, Category, CaloryCount) values ('Swainson''s francolin', 'side', 96);
insert into Food (NameOfFood, Category, CaloryCount) values ('Elk, Wapiti', 'side', 37);
insert into Food (NameOfFood, Category, CaloryCount) values ('Eland, common', 'main', 54);
insert into Food (NameOfFood, Category, CaloryCount) values ('Nutcracker, clark''s', 'main', 78);
insert into Food (NameOfFood, Category, CaloryCount) values ('Paddy heron (unidentified)', 'main', 9);
insert into Food (NameOfFood, Category, CaloryCount) values ('Lion, steller''s sea', 'side', 47);
insert into Food (NameOfFood, Category, CaloryCount) values ('Blue waxbill', 'desert', 10);
insert into Food (NameOfFood, Category, CaloryCount) values ('Godwit, hudsonian', 'side', 29);
insert into Food (NameOfFood, Category, CaloryCount) values ('Phascogale, red-tailed', 'main', 86);
insert into Food (NameOfFood, Category, CaloryCount) values ('Gray rhea', 'side', 42);
insert into Food (NameOfFood, Category, CaloryCount) values ('Great horned owl', 'desert', 59);
insert into Food (NameOfFood, Category, CaloryCount) values ('Waxbill, black-cheeked', 'side', 27);
insert into Food (NameOfFood, Category, CaloryCount) values ('Screamer, crested', 'desert', 73);
insert into Food (NameOfFood, Category, CaloryCount) values ('American marten', 'main', 83);
insert into Food (NameOfFood, Category, CaloryCount) values ('Grenadier, purple', 'main', 22);
insert into Food (NameOfFood, Category, CaloryCount) values ('Musk ox', 'main', 17);
insert into Food (NameOfFood, Category, CaloryCount) values ('Roe deer', 'side', 98);
insert into Food (NameOfFood, Category, CaloryCount) values ('Squirrel glider', 'main', 78);
insert into Food (NameOfFood, Category, CaloryCount) values ('Madagascar hawk owl', 'side', 60);
insert into Food (NameOfFood, Category, CaloryCount) values ('Mara', 'main', 1);
insert into Food (NameOfFood, Category, CaloryCount) values ('Wolf, timber', 'main', 71);
insert into Food (NameOfFood, Category, CaloryCount) values ('Goliath heron', 'desert', 65);
insert into Food (NameOfFood, Category, CaloryCount) values ('Great white pelican', 'desert', 51);
insert into Food (NameOfFood, Category, CaloryCount) values ('Golden eagle', 'side', 90);
insert into Food (NameOfFood, Category, CaloryCount) values ('Duck, comb', 'desert', 67);
insert into Food (NameOfFood, Category, CaloryCount) values ('Waved albatross', 'side', 98);
insert into Food (NameOfFood, Category, CaloryCount) values ('Buffalo, wild water', 'side', 18);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bird, secretary', 'side', 81);
insert into Food (NameOfFood, Category, CaloryCount) values ('Screamer, crested', 'main', 75);
insert into Food (NameOfFood, Category, CaloryCount) values ('Elegant crested tinamou', 'desert', 25);
insert into Food (NameOfFood, Category, CaloryCount) values ('Crane, blue', 'side', 4);
insert into Food (NameOfFood, Category, CaloryCount) values ('Cat, miner''s', 'side', 47);
insert into Food (NameOfFood, Category, CaloryCount) values ('Osprey', 'side', 4);
insert into Food (NameOfFood, Category, CaloryCount) values ('Lion, california sea', 'side', 17);
insert into Food (NameOfFood, Category, CaloryCount) values ('Arboral spiny rat', 'side', 26);
insert into Food (NameOfFood, Category, CaloryCount) values ('Dragon, netted rock', 'side', 98);
insert into Food (NameOfFood, Category, CaloryCount) values ('Whale, southern right', 'desert', 40);
insert into Food (NameOfFood, Category, CaloryCount) values ('Cockatoo, slender-billed', 'main', 88);
insert into Food (NameOfFood, Category, CaloryCount) values ('Antelope, four-horned', 'side', 41);
insert into Food (NameOfFood, Category, CaloryCount) values ('Lemur, sportive', 'side', 71);
insert into Food (NameOfFood, Category, CaloryCount) values ('Madagascar fruit bat', 'desert', 67);
insert into Food (NameOfFood, Category, CaloryCount) values ('Puna ibis', 'side', 26);
insert into Food (NameOfFood, Category, CaloryCount) values ('Lion, galapagos sea', 'desert', 48);
insert into Food (NameOfFood, Category, CaloryCount) values ('Red squirrel', 'side', 22);
insert into Food (NameOfFood, Category, CaloryCount) values ('Brown hyena', 'main', 71);
insert into Food (NameOfFood, Category, CaloryCount) values ('Jackal, asiatic', 'main', 74);
insert into Food (NameOfFood, Category, CaloryCount) values ('Red-tailed hawk', 'main', 81);
insert into Food (NameOfFood, Category, CaloryCount) values ('Nine-banded armadillo', 'main', 33);
insert into Food (NameOfFood, Category, CaloryCount) values ('Slender-billed cockatoo', 'main', 23);
insert into Food (NameOfFood, Category, CaloryCount) values ('Iguana, land', 'desert', 7);
insert into Food (NameOfFood, Category, CaloryCount) values ('Grizzly bear', 'side', 52);
insert into Food (NameOfFood, Category, CaloryCount) values ('Common nighthawk', 'main', 11);
insert into Food (NameOfFood, Category, CaloryCount) values ('Onager', 'main', 4);
insert into Food (NameOfFood, Category, CaloryCount) values ('Anteater, giant', 'desert', 60);
insert into Food (NameOfFood, Category, CaloryCount) values ('Goose, knob-nosed', 'main', 34);
insert into Food (NameOfFood, Category, CaloryCount) values ('Genoveva', 'desert', 45);
insert into Food (NameOfFood, Category, CaloryCount) values ('Western lowland gorilla', 'side', 41);
insert into Food (NameOfFood, Category, CaloryCount) values ('Baleen whale', 'main', 30);
insert into Food (NameOfFood, Category, CaloryCount) values ('Nighthawk, common', 'main', 27);
insert into Food (NameOfFood, Category, CaloryCount) values ('Crowned eagle', 'side', 44);
insert into Food (NameOfFood, Category, CaloryCount) values ('Dragon, western bearded', 'desert', 25);
insert into Food (NameOfFood, Category, CaloryCount) values ('Cat, kaffir', 'main', 87);
insert into Food (NameOfFood, Category, CaloryCount) values ('Tenrec, tailless', 'desert', 50);
insert into Food (NameOfFood, Category, CaloryCount) values ('Crow, house', 'desert', 45);
insert into Food (NameOfFood, Category, CaloryCount) values ('African polecat', 'main', 45);
insert into Food (NameOfFood, Category, CaloryCount) values ('Carmine bee-eater', 'desert', 26);
insert into Food (NameOfFood, Category, CaloryCount) values ('Common dolphin', 'main', 58);
insert into Food (NameOfFood, Category, CaloryCount) values ('American woodcock', 'side', 55);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bent-toed gecko', 'desert', 67);
insert into Food (NameOfFood, Category, CaloryCount) values ('Oryx, fringe-eared', 'side', 83);
insert into Food (NameOfFood, Category, CaloryCount) values ('Squirrel, eurasian red', 'main', 4);
insert into Food (NameOfFood, Category, CaloryCount) values ('Macaw, red and blue', 'main', 72);
insert into Food (NameOfFood, Category, CaloryCount) values ('Southern hairy-nosed wombat', 'desert', 66);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bandicoot, long-nosed', 'desert', 12);
insert into Food (NameOfFood, Category, CaloryCount) values ('Red squirrel', 'desert', 92);
insert into Food (NameOfFood, Category, CaloryCount) values ('Crab-eating fox', 'desert', 83);
insert into Food (NameOfFood, Category, CaloryCount) values ('Turkey, australian brush', 'side', 75);
insert into Food (NameOfFood, Category, CaloryCount) values ('Cat, tiger', 'side', 50);
insert into Food (NameOfFood, Category, CaloryCount) values ('Stone sheep', 'desert', 76);
insert into Food (NameOfFood, Category, CaloryCount) values ('Goanna lizard', 'desert', 34);
insert into Food (NameOfFood, Category, CaloryCount) values ('Anteater, australian spiny', 'desert', 21);
insert into Food (NameOfFood, Category, CaloryCount) values ('Tortoise, desert', 'main', 96);
insert into Food (NameOfFood, Category, CaloryCount) values ('Indian star tortoise', 'side', 6);
insert into Food (NameOfFood, Category, CaloryCount) values ('Gray heron', 'main', 82);
insert into Food (NameOfFood, Category, CaloryCount) values ('Gazelle, thomson''s', 'side', 97);
insert into Food (NameOfFood, Category, CaloryCount) values ('Crane, sandhill', 'side', 78);
insert into Food (NameOfFood, Category, CaloryCount) values ('Western grey kangaroo', 'main', 80);
insert into Food (NameOfFood, Category, CaloryCount) values ('Dove, ring', 'side', 66);
insert into Food (NameOfFood, Category, CaloryCount) values ('Trumpeter, green-winged', 'desert', 2);
insert into Food (NameOfFood, Category, CaloryCount) values ('Turkey vulture', 'desert', 97);
insert into Food (NameOfFood, Category, CaloryCount) values ('American crow', 'main', 97);
insert into Food (NameOfFood, Category, CaloryCount) values ('Brocket, red', 'side', 72);
insert into Food (NameOfFood, Category, CaloryCount) values ('Gazer, sun', 'side', 9);
insert into Food (NameOfFood, Category, CaloryCount) values ('Greater adjutant stork', 'side', 70);
insert into Food (NameOfFood, Category, CaloryCount) values ('Peccary, collared', 'side', 21);
insert into Food (NameOfFood, Category, CaloryCount) values ('Brush-tailed bettong', 'side', 88);
insert into Food (NameOfFood, Category, CaloryCount) values ('Pocket gopher (unidentified)', 'side', 66);
insert into Food (NameOfFood, Category, CaloryCount) values ('Short-beaked echidna', 'desert', 53);
insert into Food (NameOfFood, Category, CaloryCount) values ('Yak', 'side', 26);
insert into Food (NameOfFood, Category, CaloryCount) values ('Common rhea', 'desert', 73);
insert into Food (NameOfFood, Category, CaloryCount) values ('Yak', 'main', 32);
insert into Food (NameOfFood, Category, CaloryCount) values ('Cuis', 'desert', 77);
insert into Food (NameOfFood, Category, CaloryCount) values ('Coatimundi, ring-tailed', 'desert', 52);
insert into Food (NameOfFood, Category, CaloryCount) values ('Mexican wolf', 'side', 56);
insert into Food (NameOfFood, Category, CaloryCount) values ('White-eye, cape', 'desert', 24);
insert into Food (NameOfFood, Category, CaloryCount) values ('Tiger snake', 'main', 88);
insert into Food (NameOfFood, Category, CaloryCount) values ('Crake, african black', 'side', 25);
insert into Food (NameOfFood, Category, CaloryCount) values ('Sheep, stone', 'main', 92);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bahama pintail', 'side', 73);
insert into Food (NameOfFood, Category, CaloryCount) values ('Whale, southern right', 'side', 99);
insert into Food (NameOfFood, Category, CaloryCount) values ('Roe deer', 'desert', 13);
insert into Food (NameOfFood, Category, CaloryCount) values ('Vulture, black', 'side', 48);
insert into Food (NameOfFood, Category, CaloryCount) values ('Western pygmy possum', 'main', 2);
insert into Food (NameOfFood, Category, CaloryCount) values ('Black-capped capuchin', 'main', 18);
insert into Food (NameOfFood, Category, CaloryCount) values ('Weaver, sociable', 'main', 56);
insert into Food (NameOfFood, Category, CaloryCount) values ('Praying mantis (unidentified)', 'side', 63);
insert into Food (NameOfFood, Category, CaloryCount) values ('Long-necked turtle', 'main', 94);
insert into Food (NameOfFood, Category, CaloryCount) values ('House sparrow', 'desert', 55);
insert into Food (NameOfFood, Category, CaloryCount) values ('Dolphin, bottle-nose', 'side', 61);
insert into Food (NameOfFood, Category, CaloryCount) values ('Gazelle, grant''s', 'desert', 66);
insert into Food (NameOfFood, Category, CaloryCount) values ('Australian sea lion', 'side', 61);
insert into Food (NameOfFood, Category, CaloryCount) values ('Kingfisher, white-throated', 'desert', 50);
insert into Food (NameOfFood, Category, CaloryCount) values ('Pallas''s fish eagle', 'main', 66);
insert into Food (NameOfFood, Category, CaloryCount) values ('Tortoise, asian foreset', 'side', 35);
insert into Food (NameOfFood, Category, CaloryCount) values ('Whale, baleen', 'side', 94);
insert into Food (NameOfFood, Category, CaloryCount) values ('Australian spiny anteater', 'side', 42);
insert into Food (NameOfFood, Category, CaloryCount) values ('Barbet, levaillant''s', 'main', 61);
insert into Food (NameOfFood, Category, CaloryCount) values ('Nubian bee-eater', 'desert', 98);
insert into Food (NameOfFood, Category, CaloryCount) values ('Pintail, white-cheeked', 'desert', 31);
insert into Food (NameOfFood, Category, CaloryCount) values ('Squirrel, malabar', 'main', 15);
insert into Food (NameOfFood, Category, CaloryCount) values ('Kiskadee, great', 'side', 34);
insert into Food (NameOfFood, Category, CaloryCount) values ('Crane, brolga', 'main', 65);
insert into Food (NameOfFood, Category, CaloryCount) values ('Dusky gull', 'desert', 66);
insert into Food (NameOfFood, Category, CaloryCount) values ('Jackal, silver-backed', 'main', 48);
insert into Food (NameOfFood, Category, CaloryCount) values ('Goose, greylag', 'main', 89);
insert into Food (NameOfFood, Category, CaloryCount) values ('Dolphin, common', 'desert', 96);
insert into Food (NameOfFood, Category, CaloryCount) values ('Screamer, crested', 'main', 66);
insert into Food (NameOfFood, Category, CaloryCount) values ('Ground monitor (unidentified)', 'side', 55);
insert into Food (NameOfFood, Category, CaloryCount) values ('Small-clawed otter', 'main', 67);
insert into Food (NameOfFood, Category, CaloryCount) values ('Starling, greater blue-eared', 'desert', 10);
insert into Food (NameOfFood, Category, CaloryCount) values ('Wild water buffalo', 'main', 15);
insert into Food (NameOfFood, Category, CaloryCount) values ('Snowy sheathbill', 'main', 32);
insert into Food (NameOfFood, Category, CaloryCount) values ('Cattle egret', 'side', 72);
insert into Food (NameOfFood, Category, CaloryCount) values ('Ring dove', 'desert', 59);
insert into Food (NameOfFood, Category, CaloryCount) values ('African ground squirrel (unidentified)', 'side', 97);
insert into Food (NameOfFood, Category, CaloryCount) values ('Dove, emerald-spotted wood', 'side', 92);
insert into Food (NameOfFood, Category, CaloryCount) values ('Goose, cape barren', 'desert', 91);
insert into Food (NameOfFood, Category, CaloryCount) values ('Silver-backed fox', 'main', 27);
insert into Food (NameOfFood, Category, CaloryCount) values ('Black-necked stork', 'main', 6);
insert into Food (NameOfFood, Category, CaloryCount) values ('Common zebra', 'side', 58);
insert into Food (NameOfFood, Category, CaloryCount) values ('Silver gull', 'main', 75);
insert into Food (NameOfFood, Category, CaloryCount) values ('Three-banded plover', 'side', 29);
insert into Food (NameOfFood, Category, CaloryCount) values ('Asian false vampire bat', 'desert', 90);
insert into Food (NameOfFood, Category, CaloryCount) values ('Asian openbill', 'side', 51);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bird (unidentified)', 'main', 36);
insert into Food (NameOfFood, Category, CaloryCount) values ('Lion, asian', 'main', 2);
insert into Food (NameOfFood, Category, CaloryCount) values ('Common turkey', 'side', 3);
insert into Food (NameOfFood, Category, CaloryCount) values ('Fox, blue', 'side', 78);
insert into Food (NameOfFood, Category, CaloryCount) values ('Wolf, timber', 'desert', 63);
insert into Food (NameOfFood, Category, CaloryCount) values ('Puma', 'desert', 82);
insert into Food (NameOfFood, Category, CaloryCount) values ('Chipmunk, least', 'main', 4);
insert into Food (NameOfFood, Category, CaloryCount) values ('Sidewinder', 'desert', 67);
insert into Food (NameOfFood, Category, CaloryCount) values ('Cougar', 'main', 2);
insert into Food (NameOfFood, Category, CaloryCount) values ('Racer, american', 'main', 60);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bat-eared fox', 'side', 13);
insert into Food (NameOfFood, Category, CaloryCount) values ('Vulture, turkey', 'side', 13);
insert into Food (NameOfFood, Category, CaloryCount) values ('Oryx, fringe-eared', 'main', 88);
insert into Food (NameOfFood, Category, CaloryCount) values ('Long-necked turtle', 'desert', 51);
insert into Food (NameOfFood, Category, CaloryCount) values ('Legaan, ground', 'desert', 71);
insert into Food (NameOfFood, Category, CaloryCount) values ('Goldeneye, common', 'desert', 98);
insert into Food (NameOfFood, Category, CaloryCount) values ('Turtle, long-necked', 'main', 46);
insert into Food (NameOfFood, Category, CaloryCount) values ('Crested bunting', 'side', 54);
insert into Food (NameOfFood, Category, CaloryCount) values ('Skunk, western spotted', 'main', 83);
insert into Food (NameOfFood, Category, CaloryCount) values ('Lourie, grey', 'main', 5);
insert into Food (NameOfFood, Category, CaloryCount) values ('Glider, sugar', 'main', 42);
insert into Food (NameOfFood, Category, CaloryCount) values ('White-lipped peccary', 'desert', 79);
insert into Food (NameOfFood, Category, CaloryCount) values ('Stork, jabiru', 'main', 51);
insert into Food (NameOfFood, Category, CaloryCount) values ('Common turkey', 'main', 48);
insert into Food (NameOfFood, Category, CaloryCount) values ('Green vine snake', 'desert', 32);
insert into Food (NameOfFood, Category, CaloryCount) values ('Long-tailed jaeger', 'side', 25);
insert into Food (NameOfFood, Category, CaloryCount) values ('Brown hyena', 'main', 69);
insert into Food (NameOfFood, Category, CaloryCount) values ('Giant otter', 'main', 64);
insert into Food (NameOfFood, Category, CaloryCount) values ('Spoonbill, european', 'main', 14);
insert into Food (NameOfFood, Category, CaloryCount) values ('Jackal, indian', 'main', 58);
insert into Food (NameOfFood, Category, CaloryCount) values ('Woolly-necked stork', 'desert', 23);
insert into Food (NameOfFood, Category, CaloryCount) values ('Crab, red lava', 'side', 4);
insert into Food (NameOfFood, Category, CaloryCount) values ('Griffon vulture', 'main', 86);
insert into Food (NameOfFood, Category, CaloryCount) values ('Puffin, horned', 'desert', 36);
insert into Food (NameOfFood, Category, CaloryCount) values ('Cockatoo, sulfur-crested', 'main', 26);
insert into Food (NameOfFood, Category, CaloryCount) values ('Mongoose, eastern dwarf', 'desert', 53);
insert into Food (NameOfFood, Category, CaloryCount) values ('Steenbok', 'desert', 80);
insert into Food (NameOfFood, Category, CaloryCount) values ('Four-horned antelope', 'main', 63);
insert into Food (NameOfFood, Category, CaloryCount) values ('Common brushtail possum', 'desert', 11);
insert into Food (NameOfFood, Category, CaloryCount) values ('White spoonbill', 'side', 58);
insert into Food (NameOfFood, Category, CaloryCount) values ('Sheep, stone', 'main', 98);
insert into Food (NameOfFood, Category, CaloryCount) values ('Cape Barren goose', 'main', 33);
insert into Food (NameOfFood, Category, CaloryCount) values ('Verreaux''s sifaka', 'side', 43);
insert into Food (NameOfFood, Category, CaloryCount) values ('Mockingbird, galapagos', 'side', 17);
insert into Food (NameOfFood, Category, CaloryCount) values ('White-necked stork', 'main', 69);
insert into Food (NameOfFood, Category, CaloryCount) values ('Black-faced kangaroo', 'main', 67);
insert into Food (NameOfFood, Category, CaloryCount) values ('Asian red fox', 'main', 83);
insert into Food (NameOfFood, Category, CaloryCount) values ('Eagle, crowned', 'main', 3);
insert into Food (NameOfFood, Category, CaloryCount) values ('Oryx, beisa', 'desert', 26);
insert into Food (NameOfFood, Category, CaloryCount) values ('Blue racer', 'main', 91);
insert into Food (NameOfFood, Category, CaloryCount) values ('Turkey, common', 'desert', 94);
insert into Food (NameOfFood, Category, CaloryCount) values ('Turkey, australian brush', 'side', 59);
insert into Food (NameOfFood, Category, CaloryCount) values ('Yellow-bellied marmot', 'main', 50);
insert into Food (NameOfFood, Category, CaloryCount) values ('Paradoxure', 'desert', 68);
insert into Food (NameOfFood, Category, CaloryCount) values ('Red phalarope', 'desert', 5);
insert into Food (NameOfFood, Category, CaloryCount) values ('Burmese brown mountain tortoise', 'side', 14);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bat, little brown', 'main', 15);
insert into Food (NameOfFood, Category, CaloryCount) values ('Corella, long-billed', 'desert', 15);
insert into Food (NameOfFood, Category, CaloryCount) values ('Stork, saddle-billed', 'desert', 71);
insert into Food (NameOfFood, Category, CaloryCount) values ('Monkey, red howler', 'side', 55);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bottle-nose dolphin', 'desert', 91);
insert into Food (NameOfFood, Category, CaloryCount) values ('Red-shouldered glossy starling', 'desert', 85);
insert into Food (NameOfFood, Category, CaloryCount) values ('Turaco, violet-crested', 'side', 77);
insert into Food (NameOfFood, Category, CaloryCount) values ('Coatimundi, white-nosed', 'desert', 50);
insert into Food (NameOfFood, Category, CaloryCount) values ('Stork, white', 'desert', 87);
insert into Food (NameOfFood, Category, CaloryCount) values ('Spoonbill, white', 'side', 28);
insert into Food (NameOfFood, Category, CaloryCount) values ('Anteater, giant', 'desert', 10);
insert into Food (NameOfFood, Category, CaloryCount) values ('Llama', 'desert', 35);
insert into Food (NameOfFood, Category, CaloryCount) values ('White-faced tree rat', 'desert', 74);
insert into Food (NameOfFood, Category, CaloryCount) values ('Squirrel, antelope ground', 'side', 3);
insert into Food (NameOfFood, Category, CaloryCount) values ('Dama wallaby', 'main', 48);
insert into Food (NameOfFood, Category, CaloryCount) values ('Dragon, asian water', 'main', 54);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bustard, kori', 'desert', 10);
insert into Food (NameOfFood, Category, CaloryCount) values ('Gazelle, thomson''s', 'side', 4);
insert into Food (NameOfFood, Category, CaloryCount) values ('Amazon parrot (unidentified)', 'side', 39);
insert into Food (NameOfFood, Category, CaloryCount) values ('African buffalo', 'side', 70);
insert into Food (NameOfFood, Category, CaloryCount) values ('Whale, southern right', 'side', 85);
insert into Food (NameOfFood, Category, CaloryCount) values ('Genet, small-spotted', 'desert', 65);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bateleur eagle', 'main', 68);
insert into Food (NameOfFood, Category, CaloryCount) values ('Black-capped capuchin', 'main', 85);
insert into Food (NameOfFood, Category, CaloryCount) values ('Horned rattlesnake', 'main', 96);
insert into Food (NameOfFood, Category, CaloryCount) values ('Leadbeateri''s ground hornbill', 'side', 11);
insert into Food (NameOfFood, Category, CaloryCount) values ('Eagle, tawny', 'desert', 63);
insert into Food (NameOfFood, Category, CaloryCount) values ('Northern fur seal', 'main', 18);
insert into Food (NameOfFood, Category, CaloryCount) values ('African elephant', 'desert', 67);
insert into Food (NameOfFood, Category, CaloryCount) values ('Shrike, southern white-crowned', 'side', 59);
insert into Food (NameOfFood, Category, CaloryCount) values ('Grenadier, purple', 'main', 71);
insert into Food (NameOfFood, Category, CaloryCount) values ('Tiger', 'main', 64);
insert into Food (NameOfFood, Category, CaloryCount) values ('Red-breasted nuthatch', 'desert', 25);
insert into Food (NameOfFood, Category, CaloryCount) values ('Antelope ground squirrel', 'main', 24);
insert into Food (NameOfFood, Category, CaloryCount) values ('Numbat', 'desert', 77);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bird, red-billed tropic', 'desert', 47);
insert into Food (NameOfFood, Category, CaloryCount) values ('American woodcock', 'side', 48);
insert into Food (NameOfFood, Category, CaloryCount) values ('Hornbill, leadbeateri''s ground', 'desert', 73);
insert into Food (NameOfFood, Category, CaloryCount) values ('Giant armadillo', 'side', 30);
insert into Food (NameOfFood, Category, CaloryCount) values ('Dove, white-winged', 'side', 8);
insert into Food (NameOfFood, Category, CaloryCount) values ('Tawny eagle', 'side', 28);
insert into Food (NameOfFood, Category, CaloryCount) values ('Asian elephant', 'side', 83);
insert into Food (NameOfFood, Category, CaloryCount) values ('Capybara', 'side', 91);
insert into Food (NameOfFood, Category, CaloryCount) values ('Penguin, fairy', 'main', 10);
insert into Food (NameOfFood, Category, CaloryCount) values ('Seven-banded armadillo', 'desert', 96);
insert into Food (NameOfFood, Category, CaloryCount) values ('Whale, killer', 'side', 79);
insert into Food (NameOfFood, Category, CaloryCount) values ('Wallaroo, common', 'side', 9);
insert into Food (NameOfFood, Category, CaloryCount) values ('Dunnart, fat-tailed', 'desert', 31);
insert into Food (NameOfFood, Category, CaloryCount) values ('Kookaburra, laughing', 'side', 82);
insert into Food (NameOfFood, Category, CaloryCount) values ('Otter, oriental short-clawed', 'desert', 20);
insert into Food (NameOfFood, Category, CaloryCount) values ('Alligator, mississippi', 'desert', 31);
insert into Food (NameOfFood, Category, CaloryCount) values ('Nile crocodile', 'side', 68);
insert into Food (NameOfFood, Category, CaloryCount) values ('Butterfly, tropical buckeye', 'main', 73);
insert into Food (NameOfFood, Category, CaloryCount) values ('Nine-banded armadillo', 'main', 34);
insert into Food (NameOfFood, Category, CaloryCount) values ('Boa, cook''s tree', 'side', 32);
insert into Food (NameOfFood, Category, CaloryCount) values ('Steenbok', 'desert', 82);
insert into Food (NameOfFood, Category, CaloryCount) values ('Cockatoo, slender-billed', 'side', 45);
insert into Food (NameOfFood, Category, CaloryCount) values ('Turkey, australian brush', 'side', 43);
insert into Food (NameOfFood, Category, CaloryCount) values ('Colobus, magistrate black', 'main', 87);
insert into Food (NameOfFood, Category, CaloryCount) values ('Magnificent frigate bird', 'main', 66);
insert into Food (NameOfFood, Category, CaloryCount) values ('Black swan', 'main', 36);
insert into Food (NameOfFood, Category, CaloryCount) values ('Red-billed hornbill', 'desert', 25);
insert into Food (NameOfFood, Category, CaloryCount) values ('Weaver, red-billed buffalo', 'side', 29);
insert into Food (NameOfFood, Category, CaloryCount) values ('Opossum, american virginia', 'side', 18);
insert into Food (NameOfFood, Category, CaloryCount) values ('Colobus, black and white', 'desert', 28);
insert into Food (NameOfFood, Category, CaloryCount) values ('Southern screamer', 'side', 23);
insert into Food (NameOfFood, Category, CaloryCount) values ('Salmon pink bird eater tarantula', 'side', 67);
insert into Food (NameOfFood, Category, CaloryCount) values ('Waxbill, violet-eared', 'desert', 53);
insert into Food (NameOfFood, Category, CaloryCount) values ('Potoroo', 'side', 58);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bulbul, african red-eyed', 'side', 15);
insert into Food (NameOfFood, Category, CaloryCount) values ('White-bellied sea eagle', 'side', 27);
insert into Food (NameOfFood, Category, CaloryCount) values ('Eastern white pelican', 'desert', 15);
insert into Food (NameOfFood, Category, CaloryCount) values ('Clark''s nutcracker', 'side', 93);
insert into Food (NameOfFood, Category, CaloryCount) values ('North American beaver', 'desert', 2);
insert into Food (NameOfFood, Category, CaloryCount) values ('Cockatoo, long-billed', 'desert', 85);
insert into Food (NameOfFood, Category, CaloryCount) values ('White stork', 'desert', 32);
insert into Food (NameOfFood, Category, CaloryCount) values ('Cape cobra', 'main', 1);
insert into Food (NameOfFood, Category, CaloryCount) values ('Goose, andean', 'side', 21);
insert into Food (NameOfFood, Category, CaloryCount) values ('Grey phalarope', 'main', 31);
insert into Food (NameOfFood, Category, CaloryCount) values ('Bee-eater (unidentified)', 'main', 52);
insert into Food (NameOfFood, Category, CaloryCount) values ('Common goldeneye', 'desert', 33);
insert into Food (NameOfFood, Category, CaloryCount) values ('Jackrabbit, white-tailed', 'side', 46);
insert into Food (NameOfFood, Category, CaloryCount) values ('Lizard, mexican beaded', 'side', 75);
insert into Food (NameOfFood, Category, CaloryCount) values ('Flamingo, chilean', 'main', 67);
insert into Food (NameOfFood, Category, CaloryCount) values ('Otter, african clawless', 'side', 74);
insert into Food (NameOfFood, Category, CaloryCount) values ('Short-nosed bandicoot', 'main', 75);
insert into Food (NameOfFood, Category, CaloryCount) values ('Eastern diamondback rattlesnake', 'desert', 23);
insert into Food (NameOfFood, Category, CaloryCount) values ('Buttermilk snake', 'side', 79);
insert into Food (NameOfFood, Category, CaloryCount) values ('Red and blue macaw', 'main', 70);
