insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tagcat', 'Aduo', 95, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Photobug', 'Lemery', 6, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Browsecat', 'Bar-le-Duc', 85, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dabfeed', 'Banyliv', 46, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Livefish', 'Mazyr', 40, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Omba', 'Zeguo', 85, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Photojam', 'Arras', 39, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Photobug', 'Plumbangan', 68, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Photobean', 'Jinan', 29, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Edgeify', 'Káto Dhiminió', 77, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Edgeblab', 'Munde', 71, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skimia', 'Huangzhuang', 62, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Devcast', 'Amgalang', 40, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eire', 'El Refugio', 33, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Muxo', 'København', 66, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tagchat', 'Pondokrejo Wetan', 66, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Trudeo', 'Somié', 52, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kamba', 'San Lorenzo', 78, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Quinu', 'Amarillo', 29, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jabberbean', 'Gusong', 45, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Feedbug', 'San Lorenzo', 97, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kimia', 'Cabeça Gorda', 62, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oyoloo', 'Levashi', 48, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Topicblab', 'Novocheboksarsk', 10, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fivebridge', 'Słupsk', 37, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yabox', 'Dieppe', 45, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skibox', 'Kralupy nad Vltavou', 59, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtworks', 'Lianyun', 32, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('BlogXS', 'Yirga ‘Alem', 6, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Livetube', 'Maño', 99, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Youspan', 'San Pedro de Macorís', 5, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jatri', 'Lang', 1, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Pixope', 'Za‘tarah', 65, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtsphere', 'Tarłów', 64, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Aimbu', 'Dehang', 66, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twimbo', 'Kinkala', 16, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Ntag', 'Damulog', 46, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skalith', 'Quthing', 38, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yabox', 'Osapsio', 10, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tavu', 'Kamwenge', 71, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dynabox', 'Liupai', 91, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skilith', 'Sida', 79, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jaxworks', 'Sanqu', 25, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Topicstorm', 'Aveiro', 7, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Agivu', 'Real', 56, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meeveo', 'Spitak', 77, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Devpulse', 'Banjiang', 52, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('JumpXS', 'San Felipe', 65, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dynabox', 'Rerawere', 83, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Npath', 'Galveias', 42, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Shufflebeat', 'Pawłosiów', 53, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('LiveZ', 'Taiping', 88, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eabox', 'Ljungbyholm', 49, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Buzzster', 'Bibrka', 79, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rhyzio', 'Subaykhān', 33, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoomlounge', 'Tentúgal', 86, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Linktype', 'Rio das Pedras', 9, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Trilia', 'Marseille', 3, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gabtune', 'Mayahi', 93, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Browsezoom', 'Kuala Lumpur', 3, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dynabox', 'Orissaare', 77, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Browseblab', 'Bara Datu', 8, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skimia', 'Proletar', 51, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Miboo', 'Yangshuo', 78, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoomlounge', 'Cibingbin', 3, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dabvine', 'Florencia', 53, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Bubblebox', 'Surazh', 4, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Ntags', 'Cangqian', 69, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jatri', 'Bergen', 27, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Voolith', 'Caen', 38, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skimia', 'Nerekhta', 24, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realcube', 'Cesvaine', 48, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wikizz', 'Xinchengpu', 25, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gigazoom', 'Jijiazhuang', 35, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dabvine', 'Piekoszów', 58, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oozz', 'Itaberaí', 36, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wikivu', 'Tucupita', 41, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Voolith', 'Stockholm', 24, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meedoo', 'Sangallaya', 82, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skiba', 'Wenchang', 82, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twimm', 'Reims', 91, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Muxo', 'Krychaw', 97, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Ooba', 'Tëplaya Gora', 25, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kamba', 'Posadas', 86, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Edgetag', 'Colonia Neuland', 45, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Layo', 'Hushi', 8, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Nlounge', 'Bistrica ob Sotli', 64, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Leexo', 'Panzhuang', 11, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Linklinks', 'Long’an Chengxiangzhen', 43, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtmix', 'Gryfino', 5, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('InnoZ', 'Villa del Rosario', 5, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rhyloo', 'Ciparay', 69, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Devpoint', 'Tsuma', 58, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twitterbeat', 'Kostyantynivka', 15, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Izio', 'Osan', 96, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Edgepulse', 'Cachachi', 89, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wikido', 'Al Khamīs', 66, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Babbleopia', 'Xiekou', 7, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Browsetype', 'Pereiro', 89, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Photobug', 'Onokivtsi', 85, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meezzy', 'Ebu', 93, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dynazzy', 'Mabini', 34, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Quinu', 'Barwałd Średni', 79, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Brainsphere', 'Aveiro', 50, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twinder', 'Kubangeceng', 75, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Einti', 'Aveiro', 69, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fivespan', 'Dong’an', 69, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Livepath', 'Mozhaysk', 46, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Photobug', 'Niños Heroes', 3, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Podcat', 'Kuala Lumpur', 77, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Abata', 'Kalahang', 46, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kanoodle', 'Uppsala', 56, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oyope', 'Goiatuba', 76, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tavu', 'Filothéi', 84, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gabcube', 'Šenov', 39, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eadel', 'Radeče', 89, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oyoyo', 'Nizhnyaya Maktama', 70, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Agimba', 'Uppsala', 87, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Trunyx', 'Dlemer', 47, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oyoba', 'Battung', 8, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wikizz', 'Quintela', 21, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skippad', 'Bielefeld', 95, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Browsecat', 'Rora Timur', 33, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Babbleopia', 'Kademangan', 56, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Shuffletag', 'Lengji', 44, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twitternation', 'Rato', 87, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Babbleopia', 'Cochrane', 64, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Blogspan', 'Kotlovka', 21, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Devbug', 'Baitu', 58, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skyvu', 'Xihu', 19, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skidoo', 'Consolacion', 79, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yadel', 'Plavsk', 79, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Ntags', 'San Vicente Pacaya', 2, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skinte', 'Varkaus', 49, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twitternation', 'Eslāmābād', 4, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Vidoo', 'Eaubonne', 12, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rhycero', 'Oslo', 91, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yodoo', 'Bailu', 25, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Browsebug', 'Rozkishne', 29, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Omba', 'Krrabë', 83, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('JumpXS', 'Palikir - National Government Center', 93, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Leenti', 'Naxos', 33, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meetz', 'Palca', 55, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Aimbo', 'Lyntupy', 21, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Buzzshare', 'Mikun’', 1, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Flashset', 'Meicheng', 39, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Feednation', 'Cergy-Pontoise', 77, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fanoodle', 'Tanbu', 86, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yacero', 'Łopuszno', 42, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yakijo', 'Buchlovice', 49, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skaboo', 'Nandong', 60, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kwinu', 'Minchinābād', 1, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Browsebug', 'Głuchów', 38, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Devshare', 'Rodolívos', 91, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gevee', 'Saint-Pierre-des-Corps', 91, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skibox', 'Hengduo', 67, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dynabox', 'Yambol', 23, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Buzzster', 'Jämsänkoski', 42, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Snaptags', 'Sibinal', 82, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Quire', 'Baoyang', 35, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Geba', 'Taikang', 82, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skinix', 'Wangqu', 47, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yotz', 'Majzar', 94, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yodo', 'Jagna', 77, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Lazz', 'Jatobá', 89, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Abatz', 'Żywiec', 4, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Podcat', 'Stęszew', 97, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('BlogXS', 'Bayt Ūlā', 86, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Voomm', 'Butou', 73, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Avaveo', 'Cherskiy', 94, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tagchat', 'Genisséa', 88, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Quimba', 'Petaling Jaya', 82, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Centizu', 'Kafr Baţnā', 16, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Innojam', 'Metlika', 2, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Vitz', 'Loznitsa', 32, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skippad', 'Nha Trang', 24, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Browsezoom', 'Coja', 92, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kayveo', 'Dongtai', 55, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Mybuzz', 'Czarna', 17, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Browsezoom', 'La Seyne-sur-Mer', 49, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dynabox', 'Bagombong', 38, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yadel', 'Núi Sập', 63, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dazzlesphere', 'Annecy', 88, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Agimba', 'Radenković', 40, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Mydo', 'Salamanca', 75, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wikido', 'Gammad', 70, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Buzzdog', 'Uglyanets', 17, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eire', 'Bela Vista', 83, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wikibox', 'Kiupo', 3, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oba', 'Taibao', 92, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dabvine', 'Pantin', 5, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fadeo', 'Hüremt', 97, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtblab', 'Solina', 77, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('InnoZ', 'Soritor', 10, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Edgewire', 'Lanot', 55, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oodoo', 'Andong', 80, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Quimba', 'Hantsavichy', 24, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skaboo', 'Pittsburgh', 68, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dazzlesphere', 'Dayingjie', 47, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tazzy', 'Donggaocun', 92, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twinte', 'Guijalo', 77, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Flashset', 'Batan', 58, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Voomm', 'Looc', 59, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rhybox', 'Manjiang', 24, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yakijo', 'Nangang', 87, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skyble', 'Liborina', 6, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rhynoodle', 'Corona', 91, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Izio', 'Runka', 53, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gigabox', 'Pokotylivka', 28, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Feednation', 'Denver', 8, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realfire', 'Granada', 18, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Plajo', 'Lin’an', 17, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Buzzster', 'Saint-Ouen', 2, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rhyloo', 'Xinhe', 97, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Voonyx', 'Mataquescuintla', 71, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realcube', 'Oesapa', 100, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eire', 'Junín', 56, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meejo', 'Zdounky', 9, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Brightbean', 'Borzęta', 61, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gevee', 'Fīrūzābād', 36, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Feedspan', 'Jiangyan', 32, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Podcat', 'Hailang', 56, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Babblestorm', 'Eldoret', 70, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Cogilith', 'Al Abyār', 28, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Abata', 'Gornje Moštre', 83, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skalith', 'Rozsypne', 10, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dabtype', 'Maño', 58, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tazz', 'Santo Tomas', 14, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Photobug', 'Anding', 50, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meevee', 'Xuyong', 52, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eare', 'Coroico', 66, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Roombo', 'Ermelo', 82, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Babbleset', 'Qian’an', 18, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Chatterbridge', 'Tsévié', 38, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Shufflester', 'Nevers', 85, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Camimbo', 'Gaotai', 78, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twitterwire', 'Lille', 36, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kazio', 'Zishan', 94, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Flipbug', 'Tambillo', 23, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dabfeed', 'Shunhe', 78, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zooxo', 'Qingshan', 63, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twitterworks', 'Kota Kinabalu', 47, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Trilith', 'La Paloma', 79, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zooveo', 'Lávara', 7, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wikizz', 'Solčava', 64, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Muxo', 'Novopokrovskaya', 73, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kazio', 'Albuquerque', 37, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Voomm', 'Neftegorsk', 52, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dazzlesphere', 'Pho Si Suwan', 43, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gigashots', 'Lolotique', 81, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Babbleset', 'Piterka', 50, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kare', 'Xiangba', 16, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Avamm', 'Niños Heroes', 52, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Devpulse', 'Izborsk', 61, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Snaptags', 'Smara', 12, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Blogtag', 'Neundeut', 91, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realbridge', 'East Angus', 73, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Youtags', 'Korenovsk', 2, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wordify', 'Xinpu', 16, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Shufflester', 'Bairro', 94, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twimm', 'Had Kourt', 79, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zava', 'Kocēni', 41, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meevee', 'Nossa Senhora de Machede', 67, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skiba', 'Buckland', 30, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tazz', 'Paris 19', 6, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tavu', 'Ede', 95, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('LiveZ', 'Kōnosu', 76, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skimia', 'Mirosławiec', 15, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meetz', 'Valmiera', 13, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realcube', 'Villa Santa Rita', 41, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Flashspan', 'Ocucaje', 81, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtbeat', 'Aricagua', 36, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Talane', 'Jiangwakou', 11, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Topiczoom', 'Antanhol', 23, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Lazz', 'Mingelchaur', 49, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Devpoint', 'Shar’ya', 8, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tanoodle', 'Best', 83, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meejo', 'Kalpáki', 95, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Innojam', 'Babug', 10, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Plajo', 'Sinait', 53, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fatz', 'Pakalongan', 78, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gabspot', 'Adelaide', 41, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Brightdog', 'Bayt ‘Īnūn', 3, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oyondu', 'Kuniran', 41, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realblab', 'Corumbá', 89, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Trupe', 'Radenković', 100, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Midel', 'Bailingnao', 23, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kwimbee', 'Bua Yai', 33, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoonoodle', 'Pereleshino', 60, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rhycero', 'San Rafael', 85, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Photospace', 'Jamban', 72, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Midel', 'Bangkal', 16, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Avaveo', 'Tanahedang', 25, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fatz', 'Trikora', 70, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('DabZ', 'Rivne', 27, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Abatz', 'Vale de Vila', 57, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Trilia', 'Ngembo', 13, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Talane', 'Sexiong', 100, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skimia', 'Ḩalabjah', 16, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jabberbean', 'Huyunxiang', 43, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twitterbeat', 'Orosh', 26, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Devcast', 'Sŭngho 1-tong', 47, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eabox', 'Peremyshl’', 65, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Flashpoint', 'Pinheiros', 84, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('JumpXS', 'Buta', 75, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fiveclub', 'Lin’an', 30, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Babbleblab', 'Lianyi', 24, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twinte', 'Mỹ Tho', 42, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Vinder', 'Chanuman', 23, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Shuffledrive', 'Senhor do Bonfim', 21, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skalith', 'Soutelo', 15, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Mudo', 'Bélabo', 37, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtblab', 'Omišalj', 84, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wordware', 'Torreira', 55, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Linktype', 'Rantauambacang', 81, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gigaclub', 'Pasauran', 5, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Layo', 'Bondoboghila', 48, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Layo', 'Catarina', 69, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skynoodle', 'Maojia', 73, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Photobug', 'Yazman', 82, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yoveo', 'General Santos', 1, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skyvu', 'Opařany', 84, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Vidoo', 'Jayanca', 15, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meembee', 'Sabtang', 66, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Feedspan', 'Yuankeng', 64, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('DabZ', 'Itaberaba', 36, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Youspan', 'Issoire', 42, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Muxo', 'Sovetsk', 75, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Layo', 'Ipatinga', 44, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twimbo', 'Vessada', 12, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtblab', 'Guéret', 33, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skilith', 'Yashalta', 84, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Podcat', 'Ajasse Ipo', 18, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fatz', 'Sapareva Banya', 90, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skajo', 'Sinhyeon', 54, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gabtype', 'Lichtenburg', 94, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twimm', 'Bambanglipuro', 74, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Devpoint', 'Belfort', 96, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eidel', 'La Unión', 19, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Roombo', 'Lazarevac', 47, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Babblestorm', 'Daliuhang', 77, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Bluezoom', 'Tianjiazhai', 67, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meeveo', 'Soly', 77, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Izio', 'Dalongzhan', 26, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dabjam', 'Otavalo', 32, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Lazz', 'Pantalowice', 97, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Feedfire', 'Saint-Denis', 1, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Quire', 'Villa Santa Rita', 38, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Youspan', 'Donghe', 92, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dabtype', 'Shucheng Chengguanzhen', 92, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Livetube', 'Jiangchuan', 39, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Demimbu', 'Taiyanghe', 60, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Pixoboo', 'Ludza', 31, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoombox', 'Huertas', 51, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Vimbo', 'Šabac', 36, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Livepath', 'Witbank', 12, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Cogidoo', 'Sinanju', 58, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kayveo', 'Zaysan', 16, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kaymbo', 'Flushing', 4, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yombu', 'Ledenice', 21, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dabjam', 'Sesheke', 3, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Riffpath', 'Bobolice', 13, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skyble', 'Hezuoqiao', 92, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wordware', 'Tagum', 50, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yambee', 'Matala', 35, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oyonder', 'Qianyou', 42, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gigazoom', 'Zhelin', 15, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Midel', 'Reims', 17, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Edgepulse', 'Khafizan', 30, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jabbertype', 'Gafargaon', 92, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Demivee', 'Heishan', 40, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jayo', 'La Gomera', 78, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Lazzy', 'Mafra', 25, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Buzzbean', 'Ganhe', 86, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tagchat', 'Tsovazard', 12, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Flipbug', 'Paris 14', 43, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Ainyx', 'El Peñón', 43, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yozio', 'San Antonio', 36, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Ainyx', 'Jinping', 10, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dynazzy', 'Všemina', 38, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kimia', 'Karak City', 13, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Talane', 'Leran Wetan', 62, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Brightbean', 'Colonia Mauricio José Troche', 8, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Riffpath', 'Pyt-Yakh', 59, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Demizz', 'Leninskiy', 65, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meembee', 'Mendi', 1, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Youbridge', 'Kandahār', 16, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skilith', 'Breves', 98, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Leenti', 'Porsgrunn', 61, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Aibox', 'At Samat', 40, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtbeat', 'Räpina', 79, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Geba', 'Los Angeles', 90, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rhynoodle', 'Dome', 70, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twitterlist', 'Berezne', 77, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Blogtag', 'Sanyantang', 32, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Mybuzz', 'Bārkhān', 77, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zava', 'Altares', 54, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meedoo', 'La Esperanza', 97, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skajo', 'Fengle', 30, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kamba', 'Santa Teresa', 74, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skyvu', 'Chợ Chu', 61, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tavu', 'Santa Cristina Couto', 58, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Shufflebeat', 'Beselga', 27, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Buzzshare', 'Barong', 8, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Linklinks', 'Batulayang', 87, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zazio', 'Paços', 12, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rhycero', 'Sucre', 39, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meezzy', 'Baru', 9, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Trilia', 'Oulad Frej', 99, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oyoyo', 'Los Palacios', 94, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Voonyx', 'Chambéry', 18, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Edgetag', 'West Jerusalem', 45, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kazio', 'Communal', 48, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yozio', 'Tan-Tan', 48, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Quimm', 'Turus', 96, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Buzzbean', 'Limulunga', 97, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gabvine', 'Cigaluh', 85, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fivespan', 'Muonio', 31, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zooveo', 'Bassano', 28, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Browsebug', 'Otradnyy', 39, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twinder', 'Banī Khaddāsh', 11, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eidel', 'Tafeng', 6, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Mynte', 'Orlando', 47, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skinix', 'Al ‘Āliyah', 43, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Blogtags', 'Palatine', 52, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Vidoo', 'Bastia', 85, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoombeat', 'Sincelejo', 12, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Brainverse', 'Mora', 19, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dazzlesphere', 'Moulins', 8, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gigaclub', 'Weifang', 1, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dabvine', 'Odrinhas', 34, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fivespan', 'Lingquan', 51, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kwilith', 'San Miguel Ixtahuacán', 14, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rhyzio', 'Osvaldo Cruz', 97, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtsphere', 'Shuangxikou', 32, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kimia', 'Bejsce', 82, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meezzy', 'Mirkovci', 100, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jabbertype', 'Changtang', 72, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wordtune', 'Nashville', 3, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jabbersphere', 'Oenpeotnai', 44, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Youfeed', 'Magetlegar', 89, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Riffpath', 'Kryvyy Rih', 89, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yombu', 'Paty do Alferes', 15, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('DabZ', 'Xinjiang', 54, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoomdog', 'Syktyvkar', 60, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dazzlesphere', 'Krasnyy Yar', 93, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wordify', 'Jawornik Polski', 34, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kazu', 'Kaédi', 48, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Cogidoo', 'Sukamaju', 6, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Trunyx', 'Kota Kinabalu', 12, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Quinu', 'Telnice', 75, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gigabox', 'Qinghe', 63, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dabvine', 'Bangbayang Kaler', 67, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skyble', 'Rohia', 12, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rhyloo', 'Turpo', 48, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skynoodle', 'Trabulheira', 30, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Trilia', 'Tomilino', 81, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Cogilith', 'Alebtong', 3, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Browsezoom', 'Bílina Kyselka', 8, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Devify', 'Ploemeur', 16, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eadel', 'Patrída', 96, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Feedfire', 'Visim', 27, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dynabox', 'Damatou', 46, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Ntag', 'Mirandopólis', 28, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fliptune', 'Fika', 100, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Trilia', 'Huitán', 13, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Ainyx', 'Beaumont', 45, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Brainsphere', 'Pidvynohradiv', 74, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tagtune', 'San Jose', 20, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Browsezoom', 'Tabia', 71, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jabbersphere', 'Gotovlje', 71, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oyoloo', 'Al Khānkah', 40, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gevee', 'Domanín', 78, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Flashpoint', 'Angra do Heroísmo', 29, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('InnoZ', 'Hyltebruk', 49, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tavu', 'Cát Bà', 59, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Lazzy', 'Lexington', 100, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Feedfire', 'Sanguansi', 45, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tazz', 'Rentung', 67, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Vipe', 'Kuantan', 11, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twimbo', 'Klang', 2, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Latz', 'Desa Margaluyu', 79, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Brainverse', 'Bentengjawa', 4, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oyonder', 'Bungsuan', 62, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Bluejam', 'Luhe', 48, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Devcast', 'Jaguimitan', 94, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oyonder', 'Al Hadā', 73, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Nlounge', 'Gebre Guracha', 65, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Omba', 'Veiga', 34, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Quatz', 'Pysznica', 28, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dabfeed', 'Independencia', 92, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fatz', 'Shalya', 15, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Bluejam', 'Roanoke', 46, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Shufflester', 'Millet', 74, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fadeo', 'Lizhai', 62, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gigaclub', 'Takamatsu-shi', 27, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eamia', 'Pingzhuang', 17, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('LiveZ', 'Enewetak', 86, true);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wordtune', 'Taramana', 96, false);
insert into OrderFood (Name, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Shufflebeat', 'Quanyang', 49, false);
