insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Babbleset', 'Pangkalan Kasai', 79, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Babbleopia', 'Vologda', 21, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skipfire', 'Sujiazhuang', 5, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yadel', 'Tangxi', 74, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yambee', 'Tizgane', 19, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Lajo', 'Diekirch', 30, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Ozu', 'Settat', 16, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Teklist', 'Cuihuangkou', 67, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kamba', 'Xincun', 88, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Youspan', 'Regente Feijó', 3, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wikido', 'Dengmingsi', 97, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Katz', 'Tanrake Village', 14, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Buzzdog', 'Onueke', 18, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Bluejam', 'Åtvidaberg', 81, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Youspan', 'Ubonratana', 96, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skynoodle', 'Hudson', 7, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Babblestorm', 'Rouyuan', 73, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Snaptags', 'Yangshan', 12, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dynava', 'Newbiggin', 7, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twimm', 'Santo Niño', 39, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skinix', 'Mashan', 70, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtstorm', 'Mabalacat', 77, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tambee', 'Made', 62, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yakidoo', 'Morez', 98, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yotz', 'Cibogo', 53, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Livetube', 'Hanamaki', 70, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skidoo', 'Songdong', 48, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yombu', 'Karanglincak', 2, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Bubblebox', 'Pakapasan Girang', 70, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tagchat', 'Boavista', 11, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oyoloo', 'Mabalacat', 10, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wikido', 'Ängelholm', 26, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoomcast', 'St. Thomas', 8, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eare', 'El Corozo', 18, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meetz', 'Capira', 5, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Topiczoom', 'Zhongxing', 20, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Youspan', 'Bromma', 43, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Layo', 'Valença', 61, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skyvu', 'Buchou', 36, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Reallinks', 'Santa María de Ipire', 32, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Browsezoom', 'Deder', 4, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Flipbug', 'Thị Trấn Tà Lùng', 51, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Mita', 'Yuzui', 48, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skidoo', 'Ciudad Cortés', 45, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skyba', 'Nice', 53, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Shuffletag', 'Val-de-Reuil', 11, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gabvine', 'Barrie', 74, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Buzzbean', 'Mayma', 83, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gigashots', 'Pesqueira', 37, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yodo', 'Vagos', 81, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Babbleopia', 'Bajina Bašta', 1, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skippad', 'Migrate', 83, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Vitz', 'Irecê', 80, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Mita', 'Penticton', 46, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Edgepulse', 'Colonia Mauricio José Troche', 46, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Ooba', 'Santo Tomas', 28, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Cogidoo', 'Longzhong', 5, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wikizz', 'Jiaotan', 51, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skaboo', 'Hluboká nad Vltavou', 38, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skipfire', 'Delft', 50, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twinte', 'Wadeng', 92, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jaxspan', 'Amu Gulang Baolige', 34, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Edgepulse', 'Xaysetha', 40, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skaboo', 'Oranjestad', 68, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Ozu', 'Hujra', 17, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Divape', 'Bairro', 95, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Divape', 'Massy', 27, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Flipstorm', 'Tingzhou', 87, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eamia', 'Datarsitu', 58, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rhyzio', 'Roodepoort', 27, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Youspan', 'Jubung', 47, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realfire', 'Linshi', 61, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Abata', 'Burlatskoye', 18, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jayo', 'Mar del Plata', 81, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Minyx', 'Fao Rai', 82, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dazzlesphere', 'Katunayaka', 49, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skimia', 'Santa Maria', 31, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realcube', 'Mimbaan Timur', 45, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Youspan', 'Lenningen', 63, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Demimbu', 'Mölndal', 86, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Plambee', 'Daping', 41, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Trudeo', 'Dawwār Tīnjah', 23, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yakijo', 'Baturinggit Kaja', 20, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Bluezoom', 'Cigebrok', 100, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoomzone', 'Hougang', 92, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Blogspan', 'Zengfu', 73, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Pixope', 'Извор', 21, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Vinte', 'Hali', 53, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Topiczoom', 'Chenjiatan', 23, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Cogidoo', 'Kushima', 41, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Centimia', 'Ventsy', 61, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Abatz', 'Kosino', 47, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tanoodle', 'Tall Abyaḑ', 94, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yodel', 'La Carlota', 17, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jabberstorm', 'Ouro Branco', 25, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twitterbridge', 'Patenongan', 22, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoombeat', 'Nassarawa', 30, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtbeat', 'Domanín', 83, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtbridge', 'Tayginka', 8, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoonder', 'Batou', 21, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Vitz', 'Xinzhaiping', 37, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skalith', 'San Isidro', 5, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Vidoo', 'Waepau', 9, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tazzy', 'Solo', 64, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Topdrive', 'Tahe', 62, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtstorm', 'Święciechowa', 56, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fatz', 'Guadalupe', 37, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twitterbeat', 'Cagwait', 83, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Ntag', 'Trảng Bàng', 38, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fiveclub', 'Cibeureum', 11, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jaxbean', 'Borovan', 38, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meejo', 'Shuishi', 38, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Topicstorm', 'San Francisco', 72, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jayo', 'Usukhchay', 35, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skidoo', 'Ma‘lūlā', 29, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Feedbug', 'Karukh', 84, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Einti', 'Daeosin Satu', 18, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dynava', 'Plesná', 47, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skyble', 'Dobdoban', 66, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Shuffletag', 'Bellavista', 83, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Feednation', 'Roanoke', 63, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Livetube', 'Santiago', 87, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Plambee', 'Volkhovskiy', 75, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yoveo', 'Owando', 8, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zooxo', 'San Antonio Oeste', 57, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skidoo', 'Ayna', 92, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Feedbug', 'Sillamäe', 71, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Aimbu', 'Grybów', 87, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jabbercube', 'Siteía', 53, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Nlounge', 'Hexi', 52, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Camido', 'Palaiseau', 56, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Midel', 'Moanemani', 9, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Demivee', 'Liulimiao', 98, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jayo', 'Tai’an', 73, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Mycat', 'Arklow', 35, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Devpoint', 'Karengan', 24, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Pixoboo', 'Quebracho', 62, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Devbug', 'Yongshan', 17, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wordify', 'Mâcon', 82, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Roombo', 'Āzādshahr', 17, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Quimm', 'Corail', 16, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jatri', 'Mombok', 28, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yoveo', 'Whitegate', 16, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Voonyx', 'Florida', 30, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Mudo', 'Dagua', 60, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Aibox', 'Talisay', 38, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tagtune', 'Poli', 30, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Brainbox', 'Strängnäs', 48, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kazio', 'Maroanging', 26, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('JumpXS', 'La Rochelle', 2, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Vipe', 'Uga', 28, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rhynyx', 'Managua', 6, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Roombo', 'Sangkulirang', 93, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twitternation', 'Kombësi', 57, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zava', 'Novi Sad', 54, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gabspot', 'Jingcheng', 22, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Edgeclub', 'Requena', 75, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eidel', 'Sulo', 72, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fatz', 'Ban Ratsada', 18, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Agimba', 'Pasarkolot', 69, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meevee', 'Foros da Catrapona', 87, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoombeat', 'Chengzihe', 35, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Edgeclub', 'Kuching', 29, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Youopia', 'Libuganon', 60, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kazu', 'Stavyshche', 39, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Talane', 'Xindi', 4, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eadel', 'Melaka', 48, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Photobug', 'Ra-ngae', 67, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Flashspan', 'Bologoye', 61, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Quatz', 'Rezovac', 100, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Livefish', 'Capitán Solari', 30, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Vipe', 'Oslo', 14, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Flashspan', 'Nanling', 62, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yakijo', 'Houjiachuan', 93, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Edgetag', 'Winong', 50, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Trupe', 'Mora', 56, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kaymbo', 'Bojszowy Nowe', 69, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Quinu', 'Tangjia', 15, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Shuffletag', 'Iţsā', 88, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tagfeed', 'Tobilolong', 63, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Blognation', 'Licun', 19, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yadel', 'Mingyue', 75, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wordpedia', 'Tubajon', 68, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skynoodle', 'Si Ma Cai', 68, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yabox', 'Palermo', 69, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Ainyx', 'Orahovica Donja', 55, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Bluezoom', 'Liwonde', 31, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jabbercube', 'Łącko', 42, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tagcat', 'Akankpa', 79, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtsphere', 'Fengtai Chengguanzhen', 76, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Buzzshare', 'Paraiso', 46, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoomdog', 'Issy-les-Moulineaux', 53, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Photofeed', 'Itaquyry', 36, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oba', 'Palermo', 28, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eadel', 'Veternik', 62, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Browsecat', 'Pyshchug', 12, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Abata', 'Flushing', 35, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meedoo', 'Skokovi', 66, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Voonder', 'Imeni Babushkina', 79, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jaxbean', 'Kidal', 2, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realbridge', 'Labé', 43, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gevee', 'Samdrup Jongkhar', 87, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jamia', 'Brampton', 37, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Topdrive', 'Verkhnya Rozhanka', 80, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tagtune', 'Magaria', 48, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wordware', 'Foz Sousa', 81, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Bluezoom', 'Wąsosz', 76, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Minyx', 'Gunung Sugih', 4, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtblab', 'Pailin', 81, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eimbee', 'Nanshan', 89, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tazzy', 'Luba', 5, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Katz', 'Pingxi', 1, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Feednation', 'Zhengchang', 68, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gabcube', 'Geshan', 63, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Chatterbridge', 'Calachuchi', 82, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Centidel', 'Huinca Renancó', 5, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realblab', 'Klenovyy', 59, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Babblestorm', 'Ishëm', 98, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Centizu', 'Budapest', 43, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rhyzio', 'Hengdong Chengguanzhen', 4, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fiveclub', 'Al Başrah', 58, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Edgeify', 'Pamiers', 78, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gigaclub', 'Cerrito', 34, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Flipstorm', 'Xinglongquan', 85, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jetpulse', 'Idkū', 93, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yambee', 'Vanino', 22, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realmix', 'Cambebba', 53, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Youopia', 'Osielsko', 72, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Ntags', 'Tegalheras', 59, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Camido', 'Moss', 93, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tazz', 'Jinhua', 51, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dabjam', 'Ash Shāmīyah', 47, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Trilith', 'Majzar', 9, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Digitube', 'Gobernador Gálvez', 23, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skaboo', 'Jianping', 4, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jaloo', 'Longxi', 84, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skippad', 'Zhongying', 47, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jabbersphere', 'Kool Tengah', 35, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wikizz', 'Hamhŭng', 95, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yakitri', 'Denver', 61, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Mynte', 'Ngembak', 51, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yoveo', 'Koukkuniemi', 95, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oyonder', 'Jiedu', 5, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Voomm', 'Yonglong', 22, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jabberbean', 'Buriti Alegre', 41, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gigashots', 'Cunday', 6, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twitterbridge', 'Kalemie', 52, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Divanoodle', 'Borås', 28, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oodoo', 'Sangumata', 36, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realblab', 'Sundbyberg', 80, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Linkbuzz', 'Piggotts', 5, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Feedmix', 'Grevená', 14, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fadeo', 'Port Saint John’s', 65, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Flipbug', 'Imotski', 5, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realfire', 'Katori-shi', 22, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Flipstorm', 'Huajialing', 97, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realblab', 'Beruniy', 27, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jayo', 'Changshan', 9, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skimia', 'Söderhamn', 66, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twitterlist', 'Budzów', 67, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meezzy', 'Margamukti', 45, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Voolith', 'Villazón', 100, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Voomm', 'Bukid', 69, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Latz', 'Stýpsi', 30, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Mudo', 'Dapitan', 38, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Izio', 'Garunggang', 18, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yodo', 'Tuojiang', 85, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Youspan', 'Konstantinovsk', 91, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tambee', 'Pitangui', 52, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twinte', 'Tiraspol', 67, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Trilia', 'Ganjiangtou', 47, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Centidel', 'Roza', 88, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Brightbean', 'Pinaring', 71, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Buzzdog', 'San Jacinto', 6, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Topicware', 'São Pedro do Estoril', 98, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skiba', 'Mubi', 59, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Photolist', 'San Jose', 10, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fiveclub', 'Älvdalen', 74, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Devpoint', 'Ḩalabjah', 12, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tazz', 'Dicun', 89, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoomzone', 'Ressano Garcia', 81, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fiveclub', 'Altanbulag', 2, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jabbersphere', 'Wudangshan', 78, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Buzzshare', 'Крива Паланка', 36, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skalith', 'Týnec', 25, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rooxo', 'Cruz das Almas', 16, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kare', 'Kamogatachō-kamogata', 40, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jayo', 'Khalkhāl', 95, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Mudo', 'Heby', 59, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rhynoodle', 'Xagmakajor', 12, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kwideo', 'Ryazhsk', 39, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Quinu', 'Kostarea Satu', 9, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Linklinks', 'Rogóźno', 65, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yodo', 'Terny', 77, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rhybox', 'Huangtan', 5, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Ozu', 'Donghai', 57, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twitterlist', 'Gbarnga', 37, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meeveo', 'Shatian', 83, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Bubblebox', 'Changdai', 2, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Voolith', 'Sintansin', 3, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Demivee', 'Francisco Morato', 38, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Devbug', 'Qalandiyā', 53, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yamia', 'Zhoutian', 94, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jetwire', 'Sidamulya Satu', 42, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoomlounge', 'Agrínio', 91, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Omba', 'Purísima', 84, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Topicblab', 'Jiamiao', 5, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fadeo', 'Tibillo', 77, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoombeat', 'Remedios', 88, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realcube', 'Xinming', 31, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Leexo', 'Sievi', 67, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tagcat', 'Shangganshan', 62, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tambee', 'Đưc Trọng', 17, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Miboo', 'Zhendu', 64, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Blogtags', 'Toutuo', 19, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Devbug', 'Rędziny', 41, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Quamba', 'Semarang', 26, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Quimm', 'Xiadong', 65, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Pixonyx', 'Hultsfred', 88, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meedoo', 'Sapang Buho', 20, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jayo', 'Huangmao', 100, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dabfeed', 'Rongcheng', 61, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jabbercube', 'Budta', 2, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Aimbo', 'Werasari', 52, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meevee', 'Čakovec', 3, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtbeat', 'Victoria Falls', 30, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realbuzz', 'Sembon', 37, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Geba', 'Jindayris', 87, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dablist', 'Wólka Pełkińska', 38, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Leexo', 'Sagopshi', 59, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Youspan', 'Ayolas', 77, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Voonte', 'Arvika', 17, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yotz', 'Aguaí', 50, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Topiczoom', 'Pengembur Dua', 69, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Youspan', 'Ferme-Neuve', 16, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realpoint', 'Ar Ramāḑīn', 25, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Ailane', 'Shanjeev Home', 41, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoombeat', 'Zaragoza', 60, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tavu', 'Bluefields', 33, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jayo', 'Charlotte', 86, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Fadeo', 'Nguigmi', 47, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Miboo', 'Bilüü', 66, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Podcat', 'Tangnan', 30, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Myworks', 'Tegaldowo', 68, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wordware', 'Chumen', 31, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Mynte', 'København', 43, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Voonix', 'Tōno', 21, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoomlounge', 'Yola', 83, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Riffwire', 'Mingoyo', 2, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zooveo', 'Sugcad', 42, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Voomm', 'Yingshouyingzi', 53, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jaxworks', 'Dashev', 41, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kwinu', 'Shuiying', 33, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realcube', 'Sanlanbahai', 29, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Chatterpoint', 'Chimbote', 2, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Buzzbean', 'Kokkári', 10, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Muxo', 'Blagodarnyy', 48, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yozio', 'Vyšší Brod', 41, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Pixonyx', 'Nouméa', 90, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eare', 'Rio Brilhante', 35, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dynazzy', 'Kuafeu', 58, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Flipbug', 'Géfyra', 44, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jaxbean', 'Palanas', 42, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jabberbean', 'Vozuća', 62, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gabcube', 'Madrid', 4, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zazio', 'Sergiyev Posad', 24, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Aivee', 'Obrera', 95, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Chatterbridge', 'Angadanan', 7, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skalith', 'Río Grande', 34, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jetwire', 'Carbonear', 53, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wordtune', 'Izingolweni', 60, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Buzzster', 'Gaborone', 98, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wikido', 'Timba Lauk', 61, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Avamm', 'Urho', 100, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Trudeo', 'Huangtan', 69, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoombeat', 'Panyindangan', 12, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Flashdog', 'Igcocolo', 6, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skinder', 'Kamba', 75, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yacero', 'Chrast', 93, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Layo', 'Tlogocilik', 27, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Vinte', 'Uitenhage', 51, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Topicware', 'Sangallaya', 73, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Minyx', 'Canchaque', 41, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kayveo', 'Návsí u Jablunkova', 61, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gigaclub', 'Lérida', 34, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kaymbo', 'Narva', 55, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Minyx', 'Zhanghua', 21, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Buzzster', 'Ijebu-Ife', 38, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Abatz', 'Aizhai', 4, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Teklist', 'Xinan', 90, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oyondu', 'Siak Sri Indrapura', 46, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realblab', 'Pyatovskiy', 71, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tekfly', 'Boliden', 64, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realbridge', 'Datuan', 25, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dynava', 'Chilmāri', 8, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Edgepulse', 'Shanjiang', 56, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jaxworks', 'Domont', 23, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Buzzbean', 'Nova Era', 71, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oyonder', 'Stod', 58, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Browsedrive', 'Salamá', 68, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yambee', 'Benzilan', 81, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jayo', 'Ciparay', 68, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Babbleblab', 'Jembangan', 13, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Plambee', 'Thị Trấn Ngải Giao', 19, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Roombo', 'Lawrenceville', 65, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twitterbridge', 'Bahui', 30, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meemm', 'Gafanha da Encarnação', 89, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zazio', 'La Garde', 46, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oozz', 'Nová Role', 22, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meeveo', 'Tianxin', 22, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Mycat', 'Pashkovskiy', 2, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Shufflebeat', 'Yihe', 34, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Latz', 'Penteado', 77, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eimbee', 'Nemuro', 92, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Midel', 'Staryy Dobrotvir', 94, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Trudeo', 'Rutana', 42, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Lajo', 'Chenxikou', 25, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Digitube', 'Kamyshevka Vtoraya', 76, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Omba', 'Xinhua', 18, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yata', 'Nakuru', 47, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wikizz', 'Hanjia', 40, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Meezzy', 'Rendian', 14, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Innotype', 'Baishuiyang', 47, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realmix', 'Klinan', 93, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Roombo', 'Hanyuan', 41, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Wordpedia', 'Laju Kidul', 57, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtmix', 'Somanda', 81, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kare', 'Zelenchukskaya', 93, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Edgeblab', 'Al ‘Awjā', 42, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twitterbeat', 'Al Maşlūb', 31, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rhyloo', 'Wenfang', 95, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Riffpedia', 'Loma Bonita', 8, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Nlounge', 'Shaxi', 80, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Oyope', 'Niños Heroes', 57, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtsphere', 'Mŭglizh', 56, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kazio', 'Wilkes Barre', 36, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eazzy', 'Penitik', 18, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twimm', 'Guanagazapa', 1, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Tagchat', 'Talitsy', 22, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtbridge', 'Prudentópolis', 15, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Dynabox', 'Tuohua', 62, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Katz', 'Janūb as Surrah', 5, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Edgetag', 'Włosienica', 41, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skivee', 'Cangkreng', 43, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rhycero', 'Songhe', 35, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtstorm', 'Xinxu', 47, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gabcube', 'Rybnaya Sloboda', 12, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Topicblab', 'Balaklava', 42, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Ailane', 'Jacareí', 37, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Agivu', 'Watulabara', 19, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoozzy', 'Yingchuan', 98, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Geba', 'Tiflet', 77, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Rhyloo', 'Yongfa', 12, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Agivu', 'Nanping', 75, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yacero', 'Atlanta', 64, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zooveo', 'Huixian Chengguanzhen', 30, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Talane', 'Phra Phutthabat', 91, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Flashset', 'Amman', 84, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yabox', '20 de Noviembre', 73, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Photobug', 'Matmata', 96, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Brightbean', 'Punta Alta', 86, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Mita', 'Sokolovyy', 32, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Gigabox', 'La Carlota', 61, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skivee', 'Yukou', 58, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Browsebug', 'Arzila', 31, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Snaptags', 'Las Matas de Santa Cruz', 37, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Roodel', 'Santa Barbara', 84, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jabberbean', 'Bāsht', 99, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Demivee', 'Dashahe', 61, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yodel', 'Chepo', 19, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Photobug', 'Tulihe', 52, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Photojam', 'Asahbadung', 68, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jabbertype', 'Zhoupi', 36, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Pixope', 'Mauá', 2, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yambee', 'Manzurka', 43, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twitterlist', 'Padang', 31, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Janyx', 'Arboga', 43, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Bubbletube', 'Al Khawkhah', 50, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Quire', 'Debe', 56, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yata', 'Taghazout', 75, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eayo', 'Ravne', 4, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Realpoint', 'Sempol', 30, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Camimbo', 'Nor Gyugh', 78, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skajo', 'Kobryn', 99, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Jatri', 'Delmas', 99, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Vinder', 'Podstepki', 7, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Thoughtbridge', 'Shah Alam', 29, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Buzzshare', 'Iowa City', 92, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Twitterlist', 'Taytayan', 89, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Trilia', 'Santo Tomas', 20, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Eabox', 'Kaiyuan', 36, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kazu', 'Cool űrhajó', 3, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Kazu', 'Saint-Brieuc', 90, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Skajo', 'Panognawan', 19, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Quamba', 'Esil', 87, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Abata', 'Foz Sousa', 71, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Linkbridge', 'Syanno', 100, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Pixonyx', 'Erdao', 76, false);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Zoozzy', 'Pa Sang', 27, true);
insert into Restaurant (NameOfRestaurant, CityOfRestaurant, RestaurantCapacity, IsDeliveryAvalable) values ('Yodo', 'Santa Luzia', 35, true);
